### PR TITLE
fix(typo): add missing file name in import

### PR DESCRIPTION
**Pull request by devhammed**

### CODE REVIEW

**Comment by JB1905** [comment]
Hi! 😃
Thanks for PR. I think instead of `./components/App` it would be better to give the path `./App` (according to the default structure of the Create React App project).
I'd be grateful if you could change the path `./components/App` to `./App` in the docs file.

**Comment by devhammed** [comment]
@JB1905 Done 🚀🚀🚀

**Comment by JB1905** [comment]
Great 🎉
Thanks. If you found a bug, or you have an idea to improve the library, feel free to write!

**Comment by devhammed** [comment]
@JB1905 I will definitely contribute to the project 😁😁😁

**Pull request merged**
